### ISSUE TITLE
Starter produces a segfault

### ISSUE THREAD

**Issue by nicodorn** [ssaring/sportstracker#163] opened 2017-06-23 09:12 UTC
Since the kernel update to 4.8.0-56 (Ubuntu 16.04) the program starter (i.e. the file /opt/SportsTracker/SportsTracker) produces a segmentation fault. The program does not start. Exactly the same happens with the latest update 4.8.0-57. Everything works fine if one starts the system with 4.8.0-55 or older.

Workaround: Start the program directly via Java (see example below) and everything works as expected independent of the kernel version.

`java -jar /opt/SportsTracker/app/st-packager-7.4.0-jfx.jar`

**Comment by ssaring** [comment] 2017-06-23 14:21
This sounds like the used Java version is not compatible with the latest kernel update anymore. The SportsTracker deb-Package contains an embedded JRE and Java has also been updated since the release of SportsTracker 7.4.0. In your tests you're using the latest external Java runtime from the Ubuntu repository as a workaround, this works fine.

For the issue #159 I've created a Debian snapshot package of SportsTracker 7.4.1, this contains the latest Java runtime. Could you please retest this version?
You can download it here: http://www.saring.de/st-snapshots/sportstracker-7.4.1-SNAPSHOT.deb

Bye, Stefan

**Comment by nicodorn** [comment] 2017-06-23 15:41
Oh, I didn't know that. Actually I'm always updating to the latest Oracle Java runtime.

Thank you very much for the snapshot! Unfortunately I had no luck with it. The result is the same. It starts like a charm with kernel revision 55, but fails with 57 (and I assume also with 56). Though, I can use the workaround in both scenarios. (BTW: I like the little touch you gave the today number!)

Unfortunately the console doesn't give me much information:

![st](https://user-images.githubusercontent.com/14349333/27489414-c99d606c-583a-11e7-9573-588547f35754.png)

**Comment by ssaring** [comment] 2017-06-23 19:58
Thanks for testing. Strange behavior - I'll try to reproduce it on my Ubuntu 16.04 system (virtual machine).

**Comment by Schoebi** [comment] 2017-06-23 21:04
On my Kubuntu it doesn't start either anymore after kernel update from probably 4.10.0-23 to 4.10.0-24.
That doesn't look like the java thing. Any idea?

Same problem on two machines.

**Comment by nicodorn** [comment] 2017-06-23 22:55
I'm starting to believe that this is an Ubuntu bug. They must have done something to the kernel that causes the behaviour.

There are other programs that have problems, too. See e.g. the following posts and comments:
http://e2e.ti.com/support/development_tools/code_composer_studio/f/81/p/604599/2227365

It seems as if there is alread a bug report that addresses the issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=865311

The starter works again if I do the `export` described in the first comment of this posts: https://askubuntu.com/questions/927746/eclipse-crashes-with-linux-kernel-4-4-0-81-generic

`export JAVA_TOOL_OPTIONS=-Xss1280k; /opt/SportsTracker/SportsTracker`

So, Stefan, I don't think you have to investigate the bug, at least not now. I think it'll be quite probable that one of the next kernel updates will deliver a fix. I'll report whether that happens or not.

**Comment by ssaring** [comment] 2017-06-24 11:31
Thanks for the information, this looks definitely like a kernal or distribution related bug, I hope it will get fixed soon. 

So I'll close this issue, it can't be solved here. In case of needed reworks please reopen this issue with the needed infos again.

**Closed** 2017-06-24 11:31 UTC
Labels: bug, SportsTracker
