### ISSUE TITLE
Import FIT-Files - last LAP not correct

### ISSUE THREAD

**Issue by bmk555** [ssaring/sportstracker#269] opened 2024-08-20 11:07 UTC
When i import FIT-Files from my Garmin forerunner 55, the last LAP of my run is not correct (to long).

The FIT-File is correct, when i import it into the mytourbook-App.

**Comment by ssaring** [comment] 2024-08-20 19:21
Could you then please attach an example FIT file for reproducing the issue, incl. what value is not correct and what would be the expected value?

**Comment by bmk555** [comment] 2024-08-22 10:19
Hello,
here the FIT-File (zipped)
[2024-08-15-19-24-14.zip](https://github.com/user-attachments/files/16709014/2024-08-15-19-24-14.zip)

Output from Exerciseviewer (SportsTracker Vr. 8.0.1):
Lap 8: Lap Time: 1:46 min, Total Time: 19:27 min

Garmin Connect:
Lap 8: Lap Time: 1:04,5 min, Total Time: 18:45 min

**Comment by ssaring** [comment] 2024-08-22 17:05
Thanks for the test file, I've just tested it. Turns out that this is the same already known issue I've solved recently in the Pull Request #267. The total time and the last lap time are displayed properly now.

The main branch already contains the bugfix (if you want to build it by your own) and it will be part of the next SportsTracker release.

**Closed by ssaring** 2024-08-22 17:05 UTC
Labels: ExerciseViewer
