### ISSUE TITLE
GUI elements missing

### ISSUE THREAD

**Issue by MartinH80** [ssaring/sportstracker#261] opened 2023-09-04 21:20 UTC
I have build current main on Suse Tumbleweed using OpenJDK 17.0.8.1. Using KDE on Xorg. I simple downloaded the source and used 'mvn package' to build, followed by  

```java --module-path sportstracker/target/lib --add-modules javafx.controls,javafx.fxml,javafx.web -jar sportstracker/target/sportstracker-8.0.0-SNAPSHOT.jar```

to run.

I have imported 1 recorded track.

When I click 'Overview diagram', no diagram is shown. When I repeat this over and over again sometimes (about in 10% of the cases, but very random) I do see the diagram.

Console doesn't output anything during success or failure.

When I double click the imported activity in the calendar, I get a pop-up to edit it. Unfortunately no fields are shown at all. Console reports on close that it stores the activity with ID 1.

When I click 'edit preferences', no preferences are shown at all. When I close the window the console says it stores the application options. I had one of many occurrences where preferences were shown, so this seems identical issue to the diagram.

**Comment by ssaring** [comment] 2023-09-05 10:11
Hmm, sounds strange. Unfortunately I don't have any Suse / KDE / x64 system around to check this. Didn't had such issues on Ubuntu / Gnome / ARM.
I can remember there were issues caused by the KDE window manager long time ago, there were incompatibilities with the Java Runtime Environment / JavaFX implementation. Don't know whether they have been fixed or whether new ones came up.

When you launch the compiled SportsTracker from the command line, are there any exception logged into the console when the error occurs?
In Suse Tumbleweed, do you also have the package of OpenJDK 20.x available? If so, could you please test this as well? Maybe there's a fixed bug.
A test with the latest OpenJFX libraries could also be interesting.

**Comment by MartinH80** [comment] 2023-09-05 21:19
I have tried:

1. Rebuild with openjdk 20
2. Rebuild with openjdk20 + openjfx 20.0.2 (updated the version number in the pom file)
3. Rebuild with openjdk20 + openjfx 20.0.2 + start without module system

When I startup the application in situation 1, the console says:

```
(java:8058): dbind-WARNING **: 23:12:54.673: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
```

And I can't import a track as the pop-up doesn't show any fields.

When I startup the application in situation 2, the console says:
```
(java:8738): dbind-WARNING **: 23:16:49.138: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

```

And I can't import a track as the pop-up doesn't show any fields.

When I startup the application in situation 3, the console says:

```
2023-09-05 23:07:14 WARNING com.sun.javafx.application.PlatformImpl startup Unsupported JavaFX configuration: classes were loaded from 'unnamed module @24418d36' 

(java:6981): dbind-WARNING **: 23:07:14.199: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

```

And when I try to open a diagram:

```
(java:6981): Gdk-WARNING **: 23:07:49.176: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
```

**Comment by ssaring** [comment] 2023-09-06 13:42
Hmm, this does not look good. Thanks for testing with the latest versions of the OpenJDK and OpenJFX libraries. From both of them the version 21 comes in the next days, maybe it might look better then.

But currently this looks like an bug either in the OpenJDK and OpenJFX in combination with your specific Linux environment with all the libraries you're using there (KDE window manager, dbus, GTK, etc). 
In case you're using Wayland, a test with X.org might also be interesting.

Sorry for not being able to help you on that problem. On the Linux environments I've tested it runs fine (Ubuntu 22.04, X.org, Gnome).  As this does not seem to be a SportsTracker error I'll close this issue for now.

However, when you've got new insights, please share them here. Might be useful for others as well.

**Closed by ssaring** 2023-09-06 13:42 UTC

**Comment by MartinH80** [comment] 2023-09-06 14:38
When walking to the office today I decided to give it a try tonight on my laptop, which runs Fedora with Gnome. The desktop with Suse runs Xorg btw, with Wayland there is a lot of screenflickering in sportstracker.
